# Generated by Django 4.2.1 on 2023-05-27 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
