# Generated by Django 4.2.1 on 2023-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_apply_job_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
